before_script:
  - apt-get update -qq
  - apt-get install -y python python-dev
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install -r dev-requirements.txt

Flake8:
  script: flake8 .
